/*
 *  Constants.h
 *  iChains
 *
 *  Created by Brian Schau on 7/3/09.
 *  Copyright 2009 iPhoneChi.Com. All rights reserved.
 */
#ifndef CONSTANTS_H
#define CONSTANTS_H

#define STATEINTROINIT 1
#define STATEINTRORUN 2
#define STATEINTROCOLDBOOT 3
#define STATEGAMERUNNING 10
#define STATEGAMENEWLEVEL 11
#define STATEGAMELEVELCOMPLETED 12
#define STATEGAMELEVELFAILED 13
#define STATEGAMELEVELDONE 14
#define STATEGAMESWITCHLEVEL 15
#define STATEGAMEMISSIONACCOMPLISHED 16
#define STATESUBMITHISCOREINIT 30
#define STATESUBMITHISCORESEND 31
#define STATESUBMITHISCORERESULT 32
#define STATEPREFSINIT 40
#define STATEPREFSRUN 41
#define STATEMODALRUN 50
#define STATEEXIT 99

#define SOUNDBUTTONPRESS 1
#define SOUNDEXPLOSION 2
#define SOUNDFIRE 3

#define MODALTYPELOWSCORE 1
#define MODALTYPEHISCORESUBMIT (MODALTYPELOWSCORE + 1)
#define MODALTYPEMEMORYWARNING (MODALTYPEHISCORESUBMIT + 1)
#define MODALTYPENORANK (MODALTYPEMEMORYWARNING + 1)
#define MODALTYPERANK1 (MODALTYPENORANK + 1)
#define MODALTYPERANK2 (MODALTYPERANK1 + 1)
#define MODALTYPERANK3 (MODALTYPERANK2 + 1)
#define MODALTYPEOTHERRANK (MODALTYPERANK3 + 1)

#endif