#!/bin/bash

# n7210
#
# Start script for the Nokia 7210 Emulator.  Runs thru Wine so Wine must
# be installed for this work ...
#
# Created and maintained by Brian Schau <brian@schau.com>

# n7210 is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.

# n7210 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.

NOKIA="Nokia/Devices/Nokia_7210_MIDP_SDK_v1_0"
SEARCHPATH="$HOME/$NOKIA:/opt/$NOKIA:/usr/local/$NOKIA"

function IsSDK()
{
	if test -d $1 -a -s $1/bin/7210.exe -a -s $1/lib/classes.zip -a -s $1/tools/emulator.jar; then
		return 1
	fi

	return 0
}

function FindSDK()
{
	if test "$N7210_HOME"; then
		IsSDK $N7210_HOME
		if test $? -eq 1; then
			echo $N7210_HOME
			return
		else
			echo "N7210_HOME set - but seems to point to an invalid SDK" >&2
		fi
	fi

	oldIFS="$IFS";
	IFS=":"
	set -- $SEARCHPATH;
	for p; do
		IsSDK $p
		if test $? -eq 1; then
			echo $p
			break;
		fi
	done

	IFS="$oldIFS"
}

function Usage()
{
	echo "Usage: $0 [OPTIONS] file"
	echo
	echo "[OPTIONS]"
	echo "  -h        Help (this ..)"
	echo "  -m home   SDK home"
	echo
	echo "The Nokia 7210 SDK is searched for in the following directories:"
	echo
	if test "$N7210_HOME"; then
		echo "+  $N7210_HOME"
	fi

	IFS=":"
	set -- $SEARCHPATH
	for p; do
		echo "+  $p"
	done

	if test -z "$N7210_HOME"; then
		echo
		echo "Hint: Set N7210_HOME to the correct path ..."
	fi

	exit 1
}

OPTS=`getopt -o hm: -n n7210 -- "$@"` || exit 1
eval set -- "$OPTS"

sdk=""
while :; do
	case "$1" in
	-h)	Usage ;;
	-m)	sdk="$2"; shift 2 ;;
	--)	shift ; break;;
	*)	Usage ;;
	esac
done

if test -z "$1"; then
	Usage
fi

if test -s "$1"; then
	jad="$1"
elif test -s "${1}.jad"; then
	jad="${1}.jad"
else
	echo "$1 is not a valid .jad file!"
	exit
fi

jad="$(readlink -f $jad)"

if test -z "$sdk"; then
	sdk="$(FindSDK)"
	if test -z "$sdk"; then
		echo "Cannot find the Nokia 7210 SDK"
		exit 1
	fi
else
	IsSDK $sdk
	if test $? -eq 0; then
		echo "Hmmm ... supplied N7210_HOME seems to point to an invalid SDK"
		exit 1
	fi
fi

jar="${jad%.*}.jar"
if test ! -s "$jar"; then
	echo "Cannot find .jar file. .jar file must be in the same directory as the .jad file."
	echo "Furthermore, it must have exactly the same basename as the .jad-file."
	echo "Jad file is:        $jad"
	echo "Jar file should be: $jar"
	exit 1
fi

CLASSPATH="$sdk/lib/classes.zip;$jar"
cd $sdk/bin
wine 7210.exe -classpath $CLASSPATH $jad
exit 0
