all:
	@echo "Use make clean"

clean:
	rm -f *~
	rm -f BMILog/Debug/*
	rm -f BMILog/Release/*
	rm -f PalmConduitInstall/ConduitInstallDll/Debug/*
	rm -f PalmConduitInstall/ConduitInstallDll/Release/*
	rm -f PalmConduitInstall/PalmConduitInstaller/Debug/*
	rm -f PalmConduitInstall/PalmConduitInstaller/Release/*

distclean:	clean
